name: Build Check

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip

      - name: Fix script permissions
        run: |
          chmod +x workflow.sh
          ./workflow.sh fix-perm

      - name: Validate module files
        run: |
          ./workflow.sh test

      - name: Build module zip
        run: |
          ./workflow.sh build
          echo "MODULE_ZIP=$(ls *.zip 2>/dev/null || echo "")" >> $GITHUB_ENV

      - name: Verify build success
        run: |
          if [ -z "${{ env.MODULE_ZIP }}" ]; then
            echo "Error: Failed to build module zip"
            exit 1
          fi
          echo "Successfully built: ${{ env.MODULE_ZIP }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MODULE_ZIP }}
          path: ${{ env.MODULE_ZIP }}
          retention-days: 7
